Development
maximus1998g/mini-insta pull request #13
Opened 2018-07-28 15:23 UTC by maximus1998g

Начал писать тесты, пока еще разбираюсь, что к чему.
Есть ли что-то лишнее/некорректное?

2018-07-31 17:21 UTC, levchik requested changes
Не совсем понял, ты привел все миграции к одной в каждом app? Так желательно делать только при каких-то значимых для проекта событиях, например, релиз альфа-версии или рефакторинг.

По поводу покрытия тестами (то, о чем я писал в issue) обязательно обрати на это внимание и не забудь добавить версию библиотеки в requirements.txt

2018-07-31 17:21 UTC, levchik commented on loginsys/tests.py
> +    def test_user_is_not_authenticated(self):
тест называется "проверить что пользователь не авторизован" лучше называть прямым текстом то что тестируется test_user_isnt_authenticated_after_logout, и раз уже мы так назвали, то давай и проверим это, пока что тестится только то, что после логаута редирект

2018-07-31 17:21 UTC, levchik commented on loginsys/tests.py
> +class SignUpViewTestCase(TestCase):
Но ведь ты здесь не проверяешь view в принципе, только создаешь 2х пользователей через модель  и проверяешь что их 2. добавь реальный тест на  регистрацию

2018-07-31 17:21 UTC, levchik commented on post/templates/post/posts.html
> -		<p><a href="{% url 'like' post_id=post.id %}"><img src="{% static "images/like.png" %}" width="25px" height="25px"></img>
попробуй для случаев когда кавычки в кавычках использовать разные виды (например, одинарные снаружи  - двойные внутри)

2018-07-31 17:21 UTC, levchik commented on requirements.txt
> +django-environ==0.4.5
а почему уменьшилась версия?

2018-07-31 17:21 UTC, levchik commented on post/tests.py
> +    def test_published_posts(self):
это тест не на view а на модели, добавь тест на вью (заход на стр, например что там список постов находится)

2018-07-31 17:21 UTC, levchik commented on post/tests.py
> +Можно ли передать профиль через reverse?
да, конечно можно
наша задача найти урл и зайти по нему на страницу, чтобы понять, что на странице есть нужная  информация о пользователе

2018-08-01 08:25 UTC, maximus1998g commented on post/templates/post/posts.html
> -		<p><a href="{% url 'like' post_id=post.id %}"><img src="{% static "images/like.png" %}" width="25px" height="25px"></img>
хорошо

2018-08-01 08:26 UTC, maximus1998g commented on requirements.txt
> +django-environ==0.4.5
pycharm после чего-то начал ругаться на environ, прося эту версию

2018-08-01 09:35 UTC, levchik commented on requirements.txt
> +django-environ==0.4.5
думаю ты принял это за не ту ошибку, типа у тебя стоит одна версия а где-то в энве другая или глобально

короче, проверь версию которая в енве, она должна быть последней + здесь ее же и запиши

2018-08-08 07:26 UTC, levchik approved these changes

2018-08-08 07:26 UTC, merged