Development
maximus1998g/mini-insta pull request #9
Opened 2018-07-17 11:18 UTC by maximus1998g

1. Добавил, где уместно related_name
2. Добил class-based views

2018-07-18 11:36 UTC, levchik requested changes
В общем принцип работы немного у нас уплыл от первоначального: когда я отправляю тебе правки по code review ты их делаешь в этом же issue и в этом же pull request-е: просто делай новый коммит и пуши в эту же ветку.

2018-07-18 11:36 UTC, levchik commented on loginsys/forms.py
> +    # photo = forms.ImageField(widget=MyClearableFileInput)
Приучайся не оставлять закомментированный код в репо

2018-07-18 11:36 UTC, levchik commented on loginsys/views.py
> +        avatar = Profile.create(self.request.user.id)
это же не автар а профиль?)

2018-07-18 11:36 UTC, levchik commented on loginsys/views.py
> +        return redirect('/profile/me')
в любом месте проекта, будь то  шаблоны или питоновский код, не используй строковые урлы потому что они могу с легкостью поменяться - вооружись reverse()

2018-07-21 16:12 UTC, maximus1998g commented on loginsys/views.py
> +        avatar = Profile.create(self.request.user.id)
конкретно здесь у меня класс профиль содержит только аватар, поэтому так сделал. Согласен, что не корректно, поэтому исправил

2018-07-21 18:43 UTC, closed without merging